# golangci-lint v2
#
# Minimal set of linters and their options are included. You are free to add new
# linters or change setting, read RULE-0001 before!
#
# Full set of options look at the reference configuration file:
# https://github.com/golangci/golangci-lint/blob/HEAD/.golangci.reference.yml

# Defines the configuration version.
# The only possible value is "2".
version: "2"

linters:
  # Default set of linters.
  # The value can be:
  # - `standard`: https://golangci-lint.run/docs/linters/#enabled-by-default
  # - `all`: enables all linters by default.
  # - `none`: disables all linters by default.
  # - `fast`: enables only linters considered as "fast" (`golangci-lint help linters --json | jq '[ .[] | select(.fast==true) ] | map(.name)'`).
  # Default: standard
  default: none

  # Enabled the most of the linters from the list of `fast` linters.
  #
  # Excluded linters that enforce restrictive and very opionated code style:
  #  - asciicheck
  #  - cyclop
  #  - decorder
  #  - depguard
  #  - dupl
  #  - embeddedstructfieldcheck
  #  - funcorder
  #  - funlen
  #  - gocognit
  #  - gocyclo
  #  - godot
  #  - goheader
  #  - gomoddirectives
  #  - gomodguard
  #  - goprintffuncname
  #  - grouper
  #  - inamedparam
  #  - lll
  #  - maintidx
  #  - mnd
  #  - nlreturn
  #  - tagalign
  #  - testpackage
  #
  # Not need anymore:
  #  - copyloopvar fixed in Go 1.22
  #
  # Need clarify, may be we need it:
  # - errchkjson has too many occurences in our code :( But it could be useful.
  # - nestif has a lot occurences with score even more than 20 :( LLM code quality :(
  #
  enable:
    - bidichk
    - dogsled
    - dupword
    - gocheckcompilerdirectives
    - gochecknoinits
    - godoclint
    - godox
    - ineffassign
    - interfacebloat
    - iotamixing
    - misspell
    - nakedret
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - testableexamples
    - unqueryvet
    - usestdlibvars
    - whitespace
    # Additionally included some of non fast linters:
    - goconst
    - gosec
    - noctx
    - unconvert
    - unparam
    - unused

  # LINTERS SETTINGS BLOCK
  # Only for enabled linters
  settings:

    dogsled:
      # Checks assignments with too many blank identifiers.
      # Default: 2
      max-blank-identifiers: 3

    dupword:
      # Keywords for detecting duplicate words.
      # If this list is not empty, only the words defined in this list will be detected.
      # Default: []
      keywords:
        - "the"
        - "and"
        - "a"
      # Keywords used to ignore detection.
      # Default: []
      # ignore:
      #   - "0C0C"
      # Checks only comments, skip strings.
      # Default: false
      comments-only: true

    funcorder:
      # Checks that constructors are placed after the structure declaration.
      # Default: true
      constructor: true
      # Checks if the exported methods of a structure are placed before the non-exported ones.
      # Default: true
      struct-method: false
      # Checks if the constructors and/or structure methods are sorted alphabetically.
      # Default: false
      alphabetical: false

    godoclint:
      # Default set of rules to enable.
      # Possible values are: `basic`, `all` or `none`.
      # Default: `basic` (enables `pkg-doc`, `single-pkg-doc`, `start-with-name`, and `deprecated`)
      default: basic
      # List of rules to disable.
      # Default: empty
      disable:
        - pkg-doc
        - single-pkg-doc
        - require-pkg-doc
        - start-with-name
        - require-doc
        - deprecated
        - max-len
        - no-unused-link
      # A map for fine-tuning individual rules.
      # All subkeys are optional.
      options:
        max-len:
          # Maximum line length for godocs, not including the `// `, or `/*` or `*/` tokens.
          # Default: 77
          length: 127
        require-doc:
          # Ignore exported (public) symbols when applying the `require-doc` rule.
          # Default: false
          ignore-exported: true
          # Ignore unexported (private) symbols when applying the `require-doc` rule.
          # Default: true
          ignore-unexported: false
        start-with-name:
          # Include unexported symbols when applying the `start-with-name` rule.
          # Default: false
          include-unexported: false

    godox:
      # Report any comments starting with keywords, this is useful for TODO or FIXME comments that
      # might be left in the code accidentally and should be resolved before merging.
      # Default: ["TODO", "BUG", "FIXME"]
      keywords:
        # - TODO # TODOs are allowed but should have ref to the task, like "TODO: planned to fix in TASK-1234"
        # - BUG  # bugs are allowed but should have ref to the task, like "BUG: planned to fix in TASK-1234"
        - FIXME
        - OPTIMIZE # marks code that should be optimized before merging
        - HACK # marks hack-around that should be removed before merging

    iotamixing:
      # Whether to report individual consts rather than just the const block.
      # Default: false
      report-individual: true

    misspell:
      # Correct spellings using locale preferences for US or UK.
      # Setting locale to US will correct the British spelling of 'colour' to 'color'.
      # Default is to use a neutral variety of English.
      locale: US
      # Typos to ignore.
      # Should be in lower case.
      # Default: []
      # ignore-rules:
      #   - someword
      # Extra word corrections.
      # `typo` and `correction` should only contain letters.
      # The words are case-insensitive.
      # Default: []
      extra-words:
        - typo: "iff"
          correction: "if"
        - typo: "cancelation"
          correction: "cancellation"
      # Mode of the analysis:
      # - default: checks all the file content.
      # - restricted: checks only comments.
      # Default: ""
      mode: default

    tagalign:
      # Align and sort can be used together or separately.
      #
      # Whether enable align. If true, the struct tags will be aligned.
      # E.g.:
      # type FooBar struct {
      #     Bar    string `json:"bar" validate:"required"`
      #     FooFoo int8   `json:"foo_foo" validate:"required"`
      # }
      # will be formatted to:
      # type FooBar struct {
      #     Bar    string `json:"bar"     validate:"required"`
      #     FooFoo int8   `json:"foo_foo" validate:"required"`
      # }
      # Default: true.
      align: true
      # Whether enable tags sort.
      # If true, the tags will be sorted by name in ascending order.
      # E.g.: `xml:"bar" json:"bar" validate:"required"` -> `json:"bar" validate:"required" xml:"bar"`.
      # Default: true
      sort: false
      # Specify the order of tags, the other tags will be sorted by name.
      # This option will be ignored if `sort` is false.
      # Default: []
      order:
        - json
        - yaml
        - yml
        - toml
        - mapstructure
        - binding
        - validate
      # Whether enable strict style.
      # In this style, the tags will be sorted and aligned in the dictionary order,
      # and the tags with the same name will be aligned together.
      # Note: This option will be ignored if 'align' or 'sort' is false.
      # Default: false
      strict: false

    usestdlibvars:
      # Suggest the use of http.MethodXX.
      # Default: true
      http-method: false
      # Suggest the use of http.StatusXX.
      # Default: true
      http-status-code: false
      # Suggest the use of time.Month in time.Date.
      # Default: false
      time-date-month: true
      # Suggest the use of time.Weekday.String().
      # Default: true
      time-weekday: true
      # Suggest the use of time.Month.String().
      # Default: false
      time-month: true
      # Suggest the use of time.Layout.
      # Default: false
      time-layout: true
      # Suggest the use of crypto.Hash.String().
      # Default: false
      crypto-hash: true
      # Suggest the use of rpc.DefaultXXPath.
      # Default: false
      default-rpc-path: true
      # Suggest the use of sql.LevelXX.String().
      # Default: false
      sql-isolation-level: true
      # Suggest the use of tls.SignatureScheme.String().
      # Default: false
      tls-signature-scheme: true
      # Suggest the use of constant.Kind.String().
      # Default: false
      constant-kind: true

    whitespace:
      # Enforces newlines (or comments) after every multi-line if statement.
      # Default: false
      multi-if: true
      # Enforces newlines (or comments) after every multi-line function signature.
      # Default: false
      multi-func: true

    gosec:
      excludes:
        - G101 # Look for hard coded credentials
        - G104 # Errors unhandled


# Make code output clear!
#
formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    # - gci # too many conflicts :|
    - gofmt
    - swaggo

  settings:
    gci:
      # Section configuration to compare against.
      # Section names are case-insensitive and may contain parameters in ().
      # The default order of sections is `standard > default > custom > blank > dot > alias > localmodule`.
      # If `custom-order` is `true`, it follows the order of `sections` option.
      # Default: ["standard", "default"]
      sections:
        - standard # Standard section: captures all standard packages.
        - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/0xade/) # Custom section: groups all imports with the specified Prefix.
        - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
        # - alias # Alias section: contains all alias imports. This section is not present unless explicitly enabled.
        # - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
      # Checks that no inline comments are present.
      # Default: false
      no-inline-comments: true
      # Checks that no prefix comments (comment lines above an import) are present.
      # Default: false
      no-prefix-comments: true
      # Enable custom order of sections.
      # If `true`, make the section order the same as the order of `sections`.
      # Default: false
      custom-order: true
      # Drops lexical ordering for custom sections.
      # Default: false
      no-lex-order: true

# Output configuration options.
output:
  # The formats used to render issues.
  formats:
    # Prints issues in a text format with colors, line number, and linter name.
    # This format is the default format.
    text:
      # Output path can be either `stdout`, `stderr` or path to the file to write to.
      # Default: stdout
      path: stdout
      # Print linter name in the end of issue text.
      # Default: true
      print-linter-name: true
      # Print lines of code with issue.
      # Default: true
      print-issued-lines: true
      # Use colors.
      # Default: true
      colors: true


issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 50
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 30

# Options for analysis running.
run:
  # Timeout for total work, e.g. 30s, 5m, 5m30s.
  # If the value is lower or equal to 0, the timeout is disabled.
  # Default: 0 (disabled)
  timeout: 5m

  # Include test files or not.
  # Default: true
  tests: false
